server:
  port: 8080

spring:
  datasource:
    username: root
    password: DYZ2019ZB
    url: jdbc:mysql://127.0.0.1:3306/word?useSSL=true&characterEncoding=UTF-8&allowMultiQuery=true&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver

    #hikari数据库连接池
    hikari:
      pool-name: HikariCP
      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 100 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1

  #配置文件上传限制
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB

#  redis配置信息
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器端口号
    port: 6379
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    # 设置密码
#    password: "123456"
    lettuce:
      pool:
        # 最大阻塞等待时间，负数表示没有限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中最大连接数，负数表示没有限制
        max-active: 20


#自定义ES配置信息
elasticsearch:
  host: 127.0.0.1:9200

#mp的xml和实体映射
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.boot.entity


minio:
  endpoint: http://127.0.0.1:9000
  accesskey: w0E0Bt2xLWe9WusX
  secretKey: 3gTNaOQ9XoidyI6ui9tpa9lavV2TUAE0

#腾讯云短信配置
tencent:
  msm:
    id: AKIDYv66wazCpPzQn085ppdCfMxMZcWDk6E9
    secret: xiHj8b1Lgs565rQkpkT5VigPCoESTFpE
    endPoint: sms.tencentcloudapi.com
    appId: 1400772406
    signName: 邓胤喆比赛项目个人网
    templateId: 1678253

